/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarmupRouteImport } from './routes/warmup'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ReportRouteImport } from './routes/report'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as FormRouteImport } from './routes/form'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsOutlineDotjsRouteImport } from './routes/scripts.outline[.]js'
import { Route as ScriptsOutlineRouteImport } from './routes/scripts.outline'
import { Route as ScriptsAntDotjsRouteImport } from './routes/scripts.ant[.]js'
import { Route as ApiReportChatRouteImport } from './routes/api.report-chat'

const WarmupRoute = WarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsOutlineDotjsRoute = ScriptsOutlineDotjsRouteImport.update({
  id: '/scripts/outline.js',
  path: '/scripts/outline.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsOutlineRoute = ScriptsOutlineRouteImport.update({
  id: '/scripts/outline',
  path: '/scripts/outline',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsAntDotjsRoute = ScriptsAntDotjsRouteImport.update({
  id: '/scripts/ant.js',
  path: '/scripts/ant.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportChatRoute = ApiReportChatRouteImport.update({
  id: '/api/report-chat',
  path: '/api/report-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/form': typeof FormRoute
  '/loading': typeof LoadingRoute
  '/report': typeof ReportRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/warmup': typeof WarmupRoute
  '/api/report-chat': typeof ApiReportChatRoute
  '/scripts/ant.js': typeof ScriptsAntDotjsRoute
  '/scripts/outline': typeof ScriptsOutlineRoute
  '/scripts/outline.js': typeof ScriptsOutlineDotjsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/form': typeof FormRoute
  '/loading': typeof LoadingRoute
  '/report': typeof ReportRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/warmup': typeof WarmupRoute
  '/api/report-chat': typeof ApiReportChatRoute
  '/scripts/ant.js': typeof ScriptsAntDotjsRoute
  '/scripts/outline': typeof ScriptsOutlineRoute
  '/scripts/outline.js': typeof ScriptsOutlineDotjsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/form': typeof FormRoute
  '/loading': typeof LoadingRoute
  '/report': typeof ReportRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/warmup': typeof WarmupRoute
  '/api/report-chat': typeof ApiReportChatRoute
  '/scripts/ant.js': typeof ScriptsAntDotjsRoute
  '/scripts/outline': typeof ScriptsOutlineRoute
  '/scripts/outline.js': typeof ScriptsOutlineDotjsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/form'
    | '/loading'
    | '/report'
    | '/share'
    | '/summary'
    | '/warmup'
    | '/api/report-chat'
    | '/scripts/ant.js'
    | '/scripts/outline'
    | '/scripts/outline.js'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/form'
    | '/loading'
    | '/report'
    | '/share'
    | '/summary'
    | '/warmup'
    | '/api/report-chat'
    | '/scripts/ant.js'
    | '/scripts/outline'
    | '/scripts/outline.js'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/form'
    | '/loading'
    | '/report'
    | '/share'
    | '/summary'
    | '/warmup'
    | '/api/report-chat'
    | '/scripts/ant.js'
    | '/scripts/outline'
    | '/scripts/outline.js'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  FormRoute: typeof FormRoute
  LoadingRoute: typeof LoadingRoute
  ReportRoute: typeof ReportRoute
  ShareRoute: typeof ShareRoute
  SummaryRoute: typeof SummaryRoute
  WarmupRoute: typeof WarmupRoute
  ApiReportChatRoute: typeof ApiReportChatRoute
  ScriptsAntDotjsRoute: typeof ScriptsAntDotjsRoute
  ScriptsOutlineRoute: typeof ScriptsOutlineRoute
  ScriptsOutlineDotjsRoute: typeof ScriptsOutlineDotjsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warmup': {
      id: '/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof WarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/outline.js': {
      id: '/scripts/outline.js'
      path: '/scripts/outline.js'
      fullPath: '/scripts/outline.js'
      preLoaderRoute: typeof ScriptsOutlineDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/outline': {
      id: '/scripts/outline'
      path: '/scripts/outline'
      fullPath: '/scripts/outline'
      preLoaderRoute: typeof ScriptsOutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/ant.js': {
      id: '/scripts/ant.js'
      path: '/scripts/ant.js'
      fullPath: '/scripts/ant.js'
      preLoaderRoute: typeof ScriptsAntDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-chat': {
      id: '/api/report-chat'
      path: '/api/report-chat'
      fullPath: '/api/report-chat'
      preLoaderRoute: typeof ApiReportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  FormRoute: FormRoute,
  LoadingRoute: LoadingRoute,
  ReportRoute: ReportRoute,
  ShareRoute: ShareRoute,
  SummaryRoute: SummaryRoute,
  WarmupRoute: WarmupRoute,
  ApiReportChatRoute: ApiReportChatRoute,
  ScriptsAntDotjsRoute: ScriptsAntDotjsRoute,
  ScriptsOutlineRoute: ScriptsOutlineRoute,
  ScriptsOutlineDotjsRoute: ScriptsOutlineDotjsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
