/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarmupRouteImport } from './routes/warmup'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as ShareRouteImport } from './routes/share'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as FormRouteImport } from './routes/form'
import { Route as DataStationRouteImport } from './routes/data-station'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsGcDotjsRouteImport } from './routes/scripts.gc[.]js'
import { Route as ScriptsGcRouteImport } from './routes/scripts.gc'
import { Route as ApiReportChatRouteImport } from './routes/api.report-chat'

const WarmupRoute = WarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStationRoute = DataStationRouteImport.update({
  id: '/data-station',
  path: '/data-station',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsGcDotjsRoute = ScriptsGcDotjsRouteImport.update({
  id: '/scripts/gc.js',
  path: '/scripts/gc.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsGcRoute = ScriptsGcRouteImport.update({
  id: '/scripts/gc',
  path: '/scripts/gc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportChatRoute = ApiReportChatRouteImport.update({
  id: '/api/report-chat',
  path: '/api/report-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/data-station': typeof DataStationRoute
  '/form': typeof FormRoute
  '/loading': typeof LoadingRoute
  '/records': typeof RecordsRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/warmup': typeof WarmupRoute
  '/api/report-chat': typeof ApiReportChatRoute
  '/scripts/gc': typeof ScriptsGcRoute
  '/scripts/gc.js': typeof ScriptsGcDotjsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/data-station': typeof DataStationRoute
  '/form': typeof FormRoute
  '/loading': typeof LoadingRoute
  '/records': typeof RecordsRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/warmup': typeof WarmupRoute
  '/api/report-chat': typeof ApiReportChatRoute
  '/scripts/gc': typeof ScriptsGcRoute
  '/scripts/gc.js': typeof ScriptsGcDotjsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/data-station': typeof DataStationRoute
  '/form': typeof FormRoute
  '/loading': typeof LoadingRoute
  '/records': typeof RecordsRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/warmup': typeof WarmupRoute
  '/api/report-chat': typeof ApiReportChatRoute
  '/scripts/gc': typeof ScriptsGcRoute
  '/scripts/gc.js': typeof ScriptsGcDotjsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/data-station'
    | '/form'
    | '/loading'
    | '/records'
    | '/share'
    | '/summary'
    | '/warmup'
    | '/api/report-chat'
    | '/scripts/gc'
    | '/scripts/gc.js'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/data-station'
    | '/form'
    | '/loading'
    | '/records'
    | '/share'
    | '/summary'
    | '/warmup'
    | '/api/report-chat'
    | '/scripts/gc'
    | '/scripts/gc.js'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/data-station'
    | '/form'
    | '/loading'
    | '/records'
    | '/share'
    | '/summary'
    | '/warmup'
    | '/api/report-chat'
    | '/scripts/gc'
    | '/scripts/gc.js'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DataStationRoute: typeof DataStationRoute
  FormRoute: typeof FormRoute
  LoadingRoute: typeof LoadingRoute
  RecordsRoute: typeof RecordsRoute
  ShareRoute: typeof ShareRoute
  SummaryRoute: typeof SummaryRoute
  WarmupRoute: typeof WarmupRoute
  ApiReportChatRoute: typeof ApiReportChatRoute
  ScriptsGcRoute: typeof ScriptsGcRoute
  ScriptsGcDotjsRoute: typeof ScriptsGcDotjsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warmup': {
      id: '/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof WarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-station': {
      id: '/data-station'
      path: '/data-station'
      fullPath: '/data-station'
      preLoaderRoute: typeof DataStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/gc.js': {
      id: '/scripts/gc.js'
      path: '/scripts/gc.js'
      fullPath: '/scripts/gc.js'
      preLoaderRoute: typeof ScriptsGcDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/gc': {
      id: '/scripts/gc'
      path: '/scripts/gc'
      fullPath: '/scripts/gc'
      preLoaderRoute: typeof ScriptsGcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-chat': {
      id: '/api/report-chat'
      path: '/api/report-chat'
      fullPath: '/api/report-chat'
      preLoaderRoute: typeof ApiReportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DataStationRoute: DataStationRoute,
  FormRoute: FormRoute,
  LoadingRoute: LoadingRoute,
  RecordsRoute: RecordsRoute,
  ShareRoute: ShareRoute,
  SummaryRoute: SummaryRoute,
  WarmupRoute: WarmupRoute,
  ApiReportChatRoute: ApiReportChatRoute,
  ScriptsGcRoute: ScriptsGcRoute,
  ScriptsGcDotjsRoute: ScriptsGcDotjsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
